### ISSUE TITLE
Delegate Event

### ISSUE THREAD

**Issue by Gillespie59** [got5/KAWWA#136]
In order to have the most efficient components, we should use event delegation for the collapsible panels, accordions and tabs. 

Instead of attaching a click handler to each element (headers for example), it is more efficient to add it to the parent element. 

For example, for the collapsible Panel component : 

```
var $this = $(this);
var $header = $this.find(".control a");

$this.on("click", ".control a", function(event){
});
```

**Comment by Gillespie59** [comment]
Not acceptable !

**Comment by gericci** [comment]
what?!
